describe('Тест интерфейса', () => {
    before(() => {
        cy.visit('/')
    })

    it('Тест на наличие элементов', () => {
        cy.get('#header')
            .should('be.visible')
        cy.get('#task')
            .should('be.visible')
        cy.get('#label')
            .should('be.visible')
        cy.get('#input')
            .should('be.visible')
        cy.get('#clearbtn')
            .should('be.visible')
        cy.get('#deletebtn')
            .should('be.visible')
        cy.get('#errormessage')
            .should('not.visible')
        cy.get('#result')
            .should('not.visible')      
    })

    it('Тест начального состояния элементов', () => {
        cy.get('#input')
            .should('have.value','')
        cy.get('#errormessage')
            .should('have.text','')
        cy.get('#result')
            .should('have.text','')
    })

    it('Тест наличия содержимого элементов', () => {
        cy.get('#header')
            .should('have.text','Вариант №9')
        cy.get('#task')
            .should('have.text','Ввести массив не более чем из 10 трехзначных целых чисел. Удалить из массива те числа, которые удовлетворяют условию: число является простым и если к этому числу прибавить 1, то полученное число будет являться степенью двух, и степень двух так же простое число. Например, число 31 удовлетворяет заданному условию: оно простое, 31+1=25 и 5 простое. Вывести измененный массив или сообщение о том, что нет чисел, удовлетворяющих условию.')
        cy.get('#label')
            .should('have.text', 'Поле для ввода элементов массива: ')
        cy.get('#clearbtn')
            .should('have.text', 'Очистить поле')
        cy.get('#deletebtn')
            .should('have.text', 'Удалить элементы')
    })

    it('Тест на возможность ввода данных', () => {
        cy.get('#input')
            .should('have.value', '')
            .type('127')
            .should('have.value', '127')
    })

    it('Тест на управление элементами с помощью мыши и клавиатуры', () => {
        cy.reload()
        cy.get('#input')
            .should('have.value', '')
            .type('124 125 126 127 128 129 130')
            .should('have.value','124 125 126 127 128 129 130')
            .tab().tab()
            .should('have.id', 'deletebtn')
            .click()
        cy.get('#result')
            .should('have.text','Результат: 124, 125, 126, 128, 129, 130')
        cy.get('#clearbtn')
            .click()
        cy.get('#input')
            .should('have.value', '')
    })

    it('Тест на вывод итогового массива', () => {
        cy.reload()
        cy.get('#input')
            .should('have.value', '')
            .type('127 150 127 200 127 999 100 127')
            .should('have.value', '127 150 127 200 127 999 100 127')
        cy.get('#deletebtn')
            .click()
        cy.get('#result')
            .should('have.text','Результат: 150, 200, 999, 100')
    })

    it('Тест на вывод сообщения об превышении количества элементов', () =>{
        cy.reload()
        cy.get('#input')
            .should('have.value','')
            .type('101 102 103 104 105 106 107 108 109 110 111')
            .should('have.value','101 102 103 104 105 106 107 108 109 110 111')
        cy.get('#deletebtn')
            .click()
        cy.get('#errormessage')
            .should('have.text','Введено больше 10 элементов!\n\n')
    })

    it('Тест на вывод сообщения о некорректных элементах', () =>{
        cy.reload()
        cy.get('#input')
            .should('have.value','')
            .type('one 1 99 100 500 999 1000 last g24hax7')
            .should('have.value','one 1 99 100 500 999 1000 last g24hax7')
        cy.get('#deletebtn')
            .click()
        cy.get('#errormessage')
            .should('have.text','Некорректные элементы: one, 1, 99, 1000, last, g24hax7')
    })

    it('Тест на вывод всех ошибок одновременно', () => {
        cy.reload()
        cy.get('#input')
            .should('have.value','')
            .type('f1rst 200 300 400 500 mi99le  600 700 800 900 la8t')
            .should('have.value','f1rst 200 300 400 500 mi99le  600 700 800 900 la8t')
        cy.get('#deletebtn')
            .click()
        cy.get('#errormessage')
            .should('have.text','Введено больше 10 элементов!\n\nНекорректные элементы: f1rst, mi99le, la8t')
    })

    it('Тест на вывод сообщения об отсутствии элементов для удаления', () => {
        cy.reload()
        cy.get('#input')
            .should('have.value', '')
            .type('125 126 128 129')
            .should('have.value', '125 126 128 129')
        cy.get('#deletebtn')
            .click()
        cy.get('#result')
            .should('have.text','Нет чисел удовлетворяющих условию!')
    })
})
